services:

  ims_php:
    image: ims-php        # pakai image lokal yang sudah di-build
    container_name: ims-php

  ims_nginx:
    container_name: ims-nginx
    environment:
      - PHP_HOST=ims-php   # nama service di shared_network
