networks:
  default:
    name: shared_network
    external: true

services:

  ims_php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: ims-php
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./docker/php/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
    environment:
      - PHP_OPCACHE_ENABLE=1
    extra_hosts:
      - "db-host:192.168.1.136"

  ims_nginx:
    image: nginx:1.25-alpine
    container_name: ims-nginx
    restart: unless-stopped
    ports:
      - "8086:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf.template:/etc/nginx/templates/default.conf.template
    environment:
      - PHP_HOST=${PHP_HOST:-ims_php}
    depends_on:
      - ims_php
